# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

WORKDIR /app

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Upgrade pip and install the package
RUN pip install --upgrade pip

# Copy the current directory contents into the container at /app
COPY . /app

# Install the package in editable mode without running any unwanted scripts
RUN pip install .[cli] --no-cache-dir

# Expose the MCP server port
EXPOSE 8080

# Set environment variables defaults (can be overridden at runtime)
ENV MCP_TRANSPORT=stdio \
    MCP_SERVER_HOST=0.0.0.0 \
    MCP_SERVER_PORT=8080

# Run the MCP server
ENTRYPOINT ["pydbcx-mcp"]
